files:
  include: 'styleguide/**/*.scss'
  ignore:
    - 'styleguide/_themes/global/scss/rsweb-font-style.scss'
    - 'styleguide/_sass/syntax-highlighting.scss'
    - 'styleguide/_themes/derek/scss/components/rsweb-font-style.scss'
    - 'styleguide/_themes/global/scss/bootstrap_variables.scss'
    - 'styleguide/_themes/global/scss/bootstrap_overrides.scss'
    - 'styleguide/_themes/global/scss/vendor_prefixes.scss'
rules:
  no-url-protocols: 0
  class-name-format:
    - 1
    - convention: ^([a-z0-9]+([A-Z][a-z0-9]+)*)(-{1}([a-z0-9]+([A-Z][a-z0-9]+)*)){0,2}$
    - convention-explanation: 'Classes should be camelCase and separated by no more than 5 hyphens'
  mixin-name-format:
    - 1
    - convention: ^([a-z0-9]+([A-Z][a-z0-9]+)*)(-{1}([a-z0-9]+([A-Z][a-z0-9]+)*)){0,5}$
    - convention-explanation: 'Classes should be camelCase and separated by no more than 2 hyphens'
